export const CHANGE_CURRENT_ALBUM = "album/CHANGE_CURRENT_ALBUM";
export type CHANGE_CURRENT_ALBUM_TYPE = typeof CHANGE_CURRENT_ALBUM;

export const CHANGE_ENTER_LOADING = "album/CHANGE_ENTER_LOADING";
export type CHANGE_ENTER_LOADING_TYPE = typeof CHANGE_ENTER_LOADING;
