export const CHANGE_ARTIST = "singer/CHANGE_ARTIST";
export type CHANGE_ARTIST_TYPE = typeof CHANGE_ARTIST;

export const CHANGE_SONGS_OF_ARTIST = "singer/CHANGE_SONGS_OF_ARTIST";
export type CHANGE_SONGS_OF_ARTIST_TYPE = typeof CHANGE_SONGS_OF_ARTIST;

export const CHANGE_ENTER_LOADING = "singer/CHANGE_ENTER_LOADING";
export type CHANGE_ENTER_LOADING_TYPE = typeof CHANGE_ENTER_LOADING;
