export const CHANGE_SINGER_LIST = "singers/CHANGE_SINGER_LIST";
export type CHANGE_SINGER_LIST_TYPE = typeof CHANGE_SINGER_LIST;

export const CHANGE_PAGE_COUNT = "singers/CHANGE_PAGE_COUNT";
export type CHANGE_PAGE_COUNT_TYPE = typeof CHANGE_PAGE_COUNT;

export const CHANGE_ENTER_LOADING = "singers/CHANGE_ENTER_LOADING";
export type CHANGE_ENTER_LOADING_TYPE = typeof CHANGE_ENTER_LOADING;

export const CHANGE_PULL_UP_LOADING = "singers/CHANGE_PULL_UP_LOADING";
export type CHANGE_PULL_UP_LOADING_TYPE = typeof CHANGE_PULL_UP_LOADING;

export const CHANGE_PULL_DOWN_LOADING = "singers/CHANGE_PULL_DOWN_LOADING";
export type CHANGE_PULL_DOWN_LOADING_TYPE = typeof CHANGE_PULL_DOWN_LOADING;
