export const SET_CURRENT_SONG = "player/SET_CURRENT_SONG";
export type SET_CURRENT_SONG_TYPE = typeof SET_CURRENT_SONG;

export const SET_FULL_SCREEN = "player/SET_FULL_SCREEN";
export type SET_FULL_SCREEN_TYPE = typeof SET_FULL_SCREEN;

export const SET_PLAYING_STATE = "player/SET_PLAYING_STATE";
export type SET_PLAYING_STATE_TYPE = typeof SET_PLAYING_STATE;

export const SET_SEQUENCE_PLAYLIST = "player/SET_SEQUENCE_PLAYLIST";
export type SET_SEQUENCE_PLAYLIST_TYPE = typeof SET_SEQUENCE_PLAYLIST;

export const SET_PLAYLIST = "player/SET_PLAYLIST";
export type SET_PLAYLIST_TYPE = typeof SET_PLAYLIST;

export const SET_PLAY_MODE = "player/SET_PLAY_MODE";
export type SET_PLAY_MODE_TYPE = typeof SET_PLAY_MODE;

export const SET_CURRENT_INDEX = "player/SET_CURRENT_INDEX";
export type SET_CURRENT_INDEX_TYPE = typeof SET_CURRENT_INDEX;

export const SET_SHOW_PLAYLIST = "player/SET_SHOW_PLAYLIST";
export type SET_SHOW_PLAYLIST_TYPE = typeof SET_SHOW_PLAYLIST;
